### PR TITLE
Fix offline extends recursion

### LINKED ISSUE #718: Recursion error when extending Django admin templates and compressing offline
Compressor throws a recursion error when trying to compress offline and admin extension templates are present:

```
$ python /www/360i/artifact/manage.py compress

Traceback (most recent call last):
  File "/www/360i/artifact/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 286, in handle
    self.compress(sys.stdout, **options)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 181, in compress
    nodes = list(parser.walk_nodes(template))
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 150, in walk_nodes
    for node in self.walk_nodes(node, original):
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 146, in walk_nodes
    for node in self.get_nodelist(node, original):
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 128, in get_nodelist
    return handle_extendsnode(node, block_context=None, original=original)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 41, in handle_extendsnode
    return handle_extendsnode(node, block_context, original)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 41, in handle_extendsnode
    return handle_extendsnode(node, block_context, original)
  { ... CONTINUED ... }
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 30, in handle_extendsnode
    context = Context()
  File "/www/360i/local/lib/python2.7/site-packages/django/template/context.py", line 151, in __init__
    self.render_context = RenderContext()
  File "/www/360i/local/lib/python2.7/site-packages/django/template/context.py", line 34, in __init__
    self._reset_dicts(dict_)
RuntimeError: maximum recursion depth exceeded
```

This is due to the template extending a template that isn't defined in the application (admin/base_site.html is in [django.contrib.admin.templates] (https://github.com/django/django/tree/master/django/contrib/admin/templates/admin)):

```django
{% extends "admin/base_site.html" %}

{% block title %}360i{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">360i</a></h1>
{% endblock %}
```

Perhaps I missed a way to tell compressor to ignore certain templates?

### PR DESCRIPTION
**Pull request by cbjadwani**
This fixes #718 and uses tests added in #727.

Passing an empty context for each extended template was breaking django's mechanism to find correct template if the name of the parent template is same as base template by keeping a stack of 'seen' templates. This PR fixes that by using a single context when finding parent templates.

### CODE REVIEW

**Comment by yprez** [comment]
I was just trying to fix the same thing... :)

You have some errors running on Django 1.8:
```
ERROR: test_offline_django (compressor.tests.test_offline.OfflineCompressBlockSuperBaseCompressed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yuri/repos/django-compressor/compressor/tests/test_offline.py", line 153, in test_offline_django
    self._test_offline(engine='django')
  File "/home/yuri/repos/django-compressor/compressor/tests/test_offline.py", line 581, in _test_offline
    log=self.log, verbosity=self.verbosity, engine=engine)
  File "/home/yuri/repos/django-compressor/compressor/management/commands/compress.py", line 181, in compress
    nodes = list(parser.walk_nodes(template))
  File "/home/yuri/repos/django-compressor/compressor/offline/django.py", line 151, in walk_nodes
    for node in self.walk_nodes(node, original):
  File "/home/yuri/repos/django-compressor/compressor/offline/django.py", line 146, in walk_nodes
    for node in self.get_nodelist(node, original):
  File "/home/yuri/repos/django-compressor/compressor/offline/django.py", line 128, in get_nodelist
    return handle_extendsnode(node, context)
  File "/home/yuri/repos/django-compressor/compressor/offline/django.py", line 21, in handle_extendsnode
    context.render_context.setdefault(BLOCK_CONTEXT_KEY, BlockContext())
AttributeError: 'RenderContext' object has no attribute 'setdefault'
```

P.S. The travis build is failing for some other reason...

**Comment by yprez** [comment]
The build seems to be failing because of #729 , and the Django1.8 error above.

**Comment by cbjadwani** [comment]
Thanks @yprez, fixed the bug with django 1.8

Also since support for recursive templates was added Django in 1.9 (https://code.djangoproject.com/ticket/15053) I have disabled the test for below 1.9

File: compressor/tests/test_offline.py [hunk 1]
```diff
@@ -7,11 +7,13 @@
 from importlib import import_module
 
 from mock import patch
-from unittest import SkipTest
+from unittest import SkipTest, skipIf
 
+from django import VERSION as DJANGO_VERSION
```
Comment (diox) [inline compressor/tests/test_offline.py]: How about just having `import django` and `django.VERSION` later ?

File: compressor/tests/test_offline.py [hunk 2]
```diff
@@ -629,3 +631,27 @@ def _test_offline(self, engine):
         rendered_template = self._render_template(engine)
         result = (result[0], result[2])
         self.assertEqual(rendered_template, ''.join(result) + '\n')
+
+
+@skipIf(DJANGO_VERSION[0] <= 1 and DJANGO_VERSION[1] < 9, "Needs Django >= 1.9, recursive templates were fixed in Django 1.9")
```
Comment (diox) [inline compressor/tests/test_offline.py]: could just do `DJANGO_VERSION < (1, 9)` ?

File: compressor/tests/test_templates/test_extends_recursion/test_compressor_offline.html [hunk 3]
```diff
@@ -0,0 +1,6 @@
+{% load compress %}
+
+{% compress js%}
+    <script type="text/javascript">alert('test');</script>
+{% endcompress %}
+{# The real error is caused by "admin/index.html" #}
```
Comment (diox) [inline compressor/tests/test_templates/test_extends_recursion/test_compressor_offline.html]: Please change that comment now that the "error" is fixed :)

**Comment by diox** [comment]
Looks good overall. Can you add a workaround of your choice for #729 while you're at it, so that we get proper travis builds ? Thanks!

**Comment by yprez** [comment]
@cbjadwani Actually, Django 1.9 is were it was broken for me in the first place...

**Comment by cbjadwani** [comment]
I have looked at the travis build failure which is due to latest virutalenv and pip have dropping support for Python 3.2. Since 3.2 is going to be [dead soon](https://www.python.org/dev/peps/pep-0392/#id9) it makes sense to drop support here also.  Though Django is going to support 3.2 till end of this year.

**Comment by yprez** [comment]
I think it's safe to freeze pip to a lower version in 3.2, before Django removes support for it.

**Comment by yprez** [comment]
I managed to fix the travis build here: https://github.com/yprez/django-compressor/commit/592acd4093e960eee5f502bd5e3e8e01b24b4a28
But Django 1.9 still doesn't work properly...

**Comment by yprez** [comment]
A small travis bug - it says the build now passes after including the commit on my branch, but it won't be merged together with this...
I think it's best to split this mess into 2 seperate PRs, one for fixing the build and one for the #718

**Comment by cbjadwani** [comment]
@yprez thanks for the fix, tests are passing with your commit cherry-picked to this PR.

I guess we can create a separate PR with cbjadwani@a9240c0 and yprez@592acd4 for #729.

**Comment by yprez** [comment]
I created a PR for the build fixes, just to clean this up... #731

**Comment by yprez** [comment]
@cbjadwani Should I open a seperate PR for this without the 2 commits in #731, or do you want to rebase this?
Or it could be merged as is and #731 closed...

**Comment by diox** [comment]
I don't mind merging this as-is now that tests are passing.

Thanks a lot to you two for your work!

**Comment by yprez** [comment]
Great! Thanks @diox @cbjadwani !
