### ISSUE TITLE
Incompatibility with latest bs4.

### ISSUE THREAD

**Issue by carltongibson** [django-compressor/django-compressor#1279]
bs4 v4.13 makes a breaking change that causes failures like this: 

```
======================================================================
ERROR: test_css_split (compressor.tests.test_parsers.BeautifulSoupParserTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/carlton/Projects/Django/django-compressor/compressor/tests/test_parsers.py", line 116, in test_css_split
    split = self.css_node.split_contents()
  File "/Users/carlton/Projects/Django/django-compressor/compressor/css.py", line 20, in split_contents
    and elem_attribs["rel"].lower() == "stylesheet"
AttributeError: 'AttributeValueList' object has no attribute 'lower'

----------------------------------------------------------------------
```

Need to track down in [the bs4 Changelog](https://git.launchpad.net/beautifulsoup/tree/CHANGELOG#n39). 

Test dependencies are currently pinned to 4.12.3.

**Comment by mweinelt** [comment]
Did a bisect and arrived a the following commit.

```
6d529cf1147dce8158cc06f94877a711caa4c788 is the first bad commit
commit 6d529cf1147dce8158cc06f94877a711caa4c788 (HEAD, origin/4.13-attributedict)
Author: Leonard Richardson <leonardr@segfault.org>
Date:   Mon May 27 11:13:00 2024 -0400

    Fixed type checking errors.

 bs4/__init__.py            | 5 +++--
 bs4/_typing.py             | 5 +++--
 bs4/builder/__init__.py    | 2 +-
 bs4/builder/_htmlparser.py | 3 ++-
 bs4/builder/_lxml.py       | 3 ++-
 bs4/element.py             | 1 +
 6 files changed, 12 insertions(+), 7 deletions(-)
```

https://git.launchpad.net/beautifulsoup/commit/?id=6d529cf1147dce8158cc06f94877a711caa4c788

The `rel` attribute has become a list and the following change fixes most of the tests, except for one:

```patch
diff --git a/compressor/css.py b/compressor/css.py
index baaf07f..7852510 100644
--- a/compressor/css.py
+++ b/compressor/css.py
@@ -17,7 +17,7 @@ class CssCompressor(Compressor):
             if (
                 elem_name == "link"
                 and "rel" in elem_attribs
-                and elem_attribs["rel"].lower() == "stylesheet"
+                and "stylesheet" in elem_attribs["rel"]
             ):
                 basename = self.get_basename(elem_attribs["href"])
                 filename = self.get_filename(basename)
```

Transforming the list items to lowercase cause all kinds of new test failures. 

```patch
diff --git a/compressor/css.py b/compressor/css.py
index baaf07f..519b3bb 100644
--- a/compressor/css.py
+++ b/compressor/css.py
@@ -17,7 +17,7 @@ class CssCompressor(Compressor):
             if (
                 elem_name == "link"
                 and "rel" in elem_attribs
-                and elem_attribs["rel"].lower() == "stylesheet"
+                and "stylesheet" in [rel.lower() for rel in elem_attribs["rel"]]
             ):
                 basename = self.get_basename(elem_attribs["href"])
                 filename = self.get_filename(basename)
```

The following test case fails after applying the first patch.

```pytb
__________________________________________________________________________ TemplatetagTestCase.test_uppercase_rel ___________________________________________________________________________

self = <compressor.tests.test_templatetags.TemplatetagTestCase testMethod=test_uppercase_rel>

        def test_uppercase_rel(self):
            template = """{% load compress %}{% compress css %}
    <link rel="StyleSheet" href="{{ STATIC_URL }}css/one.css" type="text/css">
    <style type="text/css">p { border:5px solid green;}</style>
    <link rel="StyleSheet" href="{{ STATIC_URL }}css/two.css" type="text/css">
    {% endcompress %}"""
            out = css_tag("/static/CACHE/css/output.600674ea1d3d.css")
>           self.assertEqual(out, render(template, self.context))
E           AssertionError: '<lin[22 chars]f="/static/CACHE/css/output.600674ea1d3d.css" type="text/css">' != '<lin[22 chars]f="/static/CACHE/css/output.919e93a2fea0.css" type="text/css">'
E           - <link rel="stylesheet" href="/static/CACHE/css/output.600674ea1d3d.css" type="text/css">
E           ?                                                       ^^^^^^  ^^^^
E           + <link rel="stylesheet" href="/static/CACHE/css/output.919e93a2fea0.css" type="text/css">
E           ?                                                       ^^^^^^^^^  ^

compressor/tests/test_templatetags.py:79: AssertionError
```

**Comment by carltongibson** [comment]
@mweinelt Good work. Do you fancy opening a PR so we can have a proper look at it? 👍

**Comment by mweinelt** [comment]
I'm not sure what the proper fix is I'm afraid, given that the one failing test tests uppercase rels, which are now not lowercased anymore, but lowercasing makes a huge number of tests fail.

**Comment by carltongibson** [comment]
@mweinelt I guess I'd say, what's the minimal change to make the test pass? (Even if we don't merge **that** it can focus the discussion.)

**Comment by matthiask** [comment]
I think the issue is that the type of list-valued items isn't `list` anymore but `AttributeValueList`, and therefore the overly specific check here fails:

https://github.com/django-compressor/django-compressor/blob/3a82c435b84b5d30e7899a771b3ad77defb77b6c/compressor/parser/beautifulsoup.py#L28

A possible fix may be https://github.com/django-compressor/django-compressor/pull/1296

**Comment by charlesroelli** [comment]
Why not change `type(value) is list` to `isinstance(value, list)`?

**Comment by matthiask** [comment]
@charlesroelli You could help by reviewing and testing #1296, the type check shouldn't even be needed.

**Comment by charlesroelli** [comment]
@matthiask Thanks, it looks great.

Related commit in beautifulsoup4: https://git.launchpad.net/beautifulsoup/commit/?id=5104c454e47242dfa68e9c6c3b7659e054230017

**Comment by carltongibson** [comment]
Just to say, thanks for this. I'm lining up to do a release here during the Django 6.0 prerelease phase, and this is on my list for that.
