### ISSUE TITLE
Error with offline compression in 1.4 and django.contrib.formtools

### ISSUE THREAD

**Issue by arthurk** [django-compressor/django-compressor#527]
django-compressor offline compression in 1.4 fails when django.contrib.formtools (tested with Django 1.5 and 1.6) is installed. It worked fine in django-compressor 1.3.

```
$ python manage.py compress -f
Error parsing template /Users/arthurk/compresstest/lib/python2.7/site-packages/django/contrib/formtools/templates/formtools/preview.html: base.html
Error parsing template /Users/arthurk/compresstest/lib/python2.7/site-packages/django/contrib/formtools/templates/formtools/form.html: base.html
```

Traceback gives me:

`AttributeError: 'NoneType' object has no attribute 'child_nodelists'`
